In [1]:
import numpy as np

In [115]:
#1
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [19]:
#2
a1 = np.reshape(a, (4, 3))
a2 = np.reshape(a, (2, 6))
a3 = np.reshape(a, (12, 1))
a4 = np.reshape(a, (6, 2))
a5 = np.reshape(a, (3, 4))
a1, a2, a3, a4, a5

(array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]]),
 array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]))

In [116]:
#3
a1 = np.reshape(a, (-1, 3))
a2 = np.reshape(a, (-1, 6))
a3 = np.reshape(a, (-1, 1))
a4 = np.reshape(a, (2, -1))
a5 = np.reshape(a, (4, -1))
a1, a2, a3, a4, a5

(array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]))

In [121]:
#4
a = np.arange(0,12)
a1 = a.reshape(12,1)
print('a', a)
print('a1', a1)
# массив Numpy a и одномерный массив а1 выглядят по-разному, поэтому массив а нельзя назвать одномерным массивом

a [ 0  1  2  3  4  5  6  7  8  9 10 11]
a1 [[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]


In [35]:
#5
m = np.random.randn(3,4)
print(m)
o = m.flatten()
print(o)
m.size == o.size

[[-3.03982595  0.61545258  0.80859152  0.34775164]
 [-0.55042866 -1.01012778  1.62312679 -1.33250213]
 [-1.21907443  0.96841273 -0.85058372  0.20803804]]
[-3.03982595  0.61545258  0.80859152  0.34775164 -0.55042866 -1.01012778
  1.62312679 -1.33250213 -1.21907443  0.96841273 -0.85058372  0.20803804]


True

In [53]:
#6
a = np.arange(20, 0, -2)
print(a)
print(a.shape)

[20 18 16 14 12 10  8  6  4  2]
(10,)


In [51]:
#7
b = np.arange(20, 1, -2).reshape(1,10)
print(b)
print(b.shape)

[[20 18 16 14 12 10  8  6  4  2]]
(1, 10)


Массив а - одномерный, массив в - двумерный

In [70]:
#8
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [71]:
b = np.ones((3,2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [72]:
v = np.vstack((a,b))
v.size

10

In [128]:
#9
a = np.arange(0,12)
A = a.reshape(4,3)
At = A.T
B = np.dot(A,At)
print('B', B)
print(B.size)
print(B.shape)
det = np.linalg.det(B)
print(det)

B [[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
16
(4, 4)
0.0


Размер матрицы В = 16. Вычислить обратную матрицу для матрицы В не получиться, потому что детерминант равен 0.

In [90]:
#10
np.random.seed(42)
np.random.randint(1,5)

3

In [122]:
#11
c = np.random.randint(0,16,16)
print('c',c)

c [ 7  4 15 12  1 14  4  7  9  8 11 11 11 12  8 12]


In [126]:
#12
C = c.reshape(4,4)
print('C',C)
D = B + (C*10)
print('D',D)
D_det = np.linalg.det(D)
D_rank = np.linalg.matrix_rank(D)
D_inv = np.linalg.inv(D)
print('D_det', D_det)
print('D_rank', D_rank)

C [[ 7  4 15 12]
 [ 1 14  4  7]
 [ 9  8 11 11]
 [11 12  8 12]]
D [[ 75  54 173 152]
 [ 24 190 126 192]
 [113 166 259 322]
 [142 242 292 422]]
D_det 18745999.999999993
D_rank 4


In [130]:
#13
D_inv[D_inv > 0] = 1
D_inv[D_inv < 0] = 0
check = D_inv[(D_inv != 1) & (D_inv != 0)]
print('check', check)
print('D_inv', D_inv)
E = np.where(D_inv, B, C)
print('E', E)
print('E_shape', E.shape)
print('B', B)
print('C',C)

check []
D_inv [[1. 0. 0. 1.]
 [1. 1. 0. 1.]
 [1. 1. 1. 0.]
 [0. 0. 1. 0.]]
E [[  5   4  15  32]
 [ 14  50   4 122]
 [ 23  86 149  11]
 [ 11  12 212  12]]
E_shape (4, 4)
B [[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
C [[ 7  4 15 12]
 [ 1 14  4  7]
 [ 9  8 11 11]
 [11 12  8 12]]
