1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно.

In [4]:
import numpy as np
a = np.linspace(12, 23, 12)
a

array([12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.])

2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [13]:
a1 = np.reshape(a, (4, 3))
a2 = np.reshape(a, (2, 6))
a3 = np.reshape(a, (12, 1))
a4 = np.reshape(a, (6, 2))
a5 = np.reshape(a, (3, 4))
a1, a2, a3, a4, a5

(array([[12., 13., 14.],
        [15., 16., 17.],
        [18., 19., 20.],
        [21., 22., 23.]]),
 array([[12., 13., 14., 15., 16., 17.],
        [18., 19., 20., 21., 22., 23.]]),
 array([[12.],
        [13.],
        [14.],
        [15.],
        [16.],
        [17.],
        [18.],
        [19.],
        [20.],
        [21.],
        [22.],
        [23.]]),
 array([[12., 13.],
        [14., 15.],
        [16., 17.],
        [18., 19.],
        [20., 21.],
        [22., 23.]]),
 array([[12., 13., 14., 15.],
        [16., 17., 18., 19.],
        [20., 21., 22., 23.]]))

3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [9]:
a1 = np.reshape(a, (-1, 3))
a2 = np.reshape(a, (-1, 6))
a3 = np.reshape(a, (-1, 4))
a4 = np.reshape(a, (2, -1))
a5 = np.reshape(a, (3, -1))
a1, a2, a3, a4, a5

(array([[12., 13., 14.],
        [15., 16., 17.],
        [18., 19., 20.],
        [21., 22., 23.]]),
 array([[12., 13., 14., 15., 16., 17.],
        [18., 19., 20., 21., 22., 23.]]),
 array([[12., 13., 14., 15.],
        [16., 17., 18., 19.],
        [20., 21., 22., 23.]]),
 array([[12., 13., 14., 15., 16., 17.],
        [18., 19., 20., 21., 22., 23.]]),
 array([[12., 13., 14., 15.],
        [16., 17., 18., 19.],
        [20., 21., 22., 23.]]))

4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

НЕТ

5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [14]:
c = np.random.randn(3,4)
c

array([[-2.24911658,  0.04005406,  0.47590938, -0.27654683],
       [ 0.11730036, -1.43915267,  0.55871281,  0.60553233],
       [-1.69681299,  1.17938662,  0.76962046, -1.1653944 ]])

In [15]:
c.size

12

In [18]:
d = c.flatten()

array([-2.24911658,  0.04005406,  0.47590938, -0.27654683,  0.11730036,
       -1.43915267,  0.55871281,  0.60553233, -1.69681299,  1.17938662,
        0.76962046, -1.1653944 ])

6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [8]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [9]:
a.shape

(10,)

In [10]:
a.size

10

7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [5]:
b = np.arange(20, 1, -2)

In [6]:
f = b.reshape(1,10)

In [34]:
f.shape

(1, 10)

In [7]:
f.size

10

Массив а - одномерный, массив b - двумерный.

8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [29]:
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [30]:
b = np.ones((3, 2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [31]:
v = np.vstack((a, b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [32]:
v.size

10

9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [37]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [38]:
a.shape

(12,)

In [39]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [40]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [55]:
B = A @ At
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [45]:
det = np.linalg.det(B)
det

0.0

In [42]:
B_inv = np.linalg.inv(B)
B_inv

LinAlgError: Singular matrix

Матрица B имеет размер 4х4. Обратную матрицу не получится вычислить, потому что определитель матрицы B равен 0.

10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [46]:
np.random.seed(42)

In [47]:
a = np.random.randint(2, 56, 5)
a

array([40, 53, 30, 16, 44])

In [48]:
a

array([40, 53, 30, 16, 44])

11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [50]:
c = np.random.randint(0, 16, 16)
c

array([ 7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4,  3,  7,  7,  2,  5])

12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [54]:
C = c.reshape(4, 4)
C

array([[ 7, 12,  4,  6],
       [ 9,  2,  6, 10],
       [10,  7,  4,  3],
       [ 7,  7,  2,  5]])

In [57]:
D = B + (C*10)
D

array([[ 75, 134,  63,  92],
       [104,  70, 146, 222],
       [123, 156, 189, 242],
       [102, 192, 232, 352]])

In [60]:
det = np.linalg.det(D)
det

-57500799.99999996

In [61]:
rank = np.linalg.matrix_rank(D)
rank

4

In [62]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.0091797 ,  0.01478936, -0.00057599, -0.01133062],
       [ 0.00726703, -0.00796476, -0.00066816,  0.00358325],
       [-0.0223656 , -0.02002824,  0.03547429, -0.00591157],
       [ 0.0081171 ,  0.01325929, -0.02284942,  0.00806597]])

In [ ]:
13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. 
Убедитесь, что в матрице D_inv остались только нули и единицы. 
С помощью функции numpy.where, используя матрицу D_inv в качестве маски, 
а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  
Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, 
должны быть равны соответствующему элементу матрицы B, 
а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, 
должны быть равны соответствующему элементу матрицы C.

In [64]:
D_inv[(D_inv < 0)] = 0
D_inv[(D_inv > 0)] = 1
D_inv

array([[1., 1., 0., 0.],
       [1., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 1., 0., 1.]])

In [65]:
E = np.where(D_inv, B, C)
E

array([[  5,  14,   4,   6],
       [ 14,   2,   6, 122],
       [ 10,   7, 149,   3],
       [ 32, 122,   2, 302]])